/* Regenerate assets/js/reference.js — the numbers the real hemispheR-py produces
   on a fixed set of synthetic canopies.

   usage: node tools/make_reference.mjs <path/to/hemispheR-py/core/hemispherR-py.py>

   Needs Python with numpy, pandas and Pillow (the dependencies of hemispheR-py).
   The page and CI hold the JavaScript port to these numbers — see tools/verify.mjs.
   Re-run this only if canopy.js's scene generator changes or hemispheR-py does. */
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { encodePNG } from './png.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const Canopy = require('../assets/js/canopy.js');

const corePath = process.argv[2] && resolve(process.argv[2]);
if (!corePath) {
  console.error('usage: node tools/make_reference.mjs <path/to/hemispherR-py.py>');
  process.exit(2);
}

const SIZE = 384;
const base = { size: SIZE, channel: 3, gamma: 0.85, zonal: true, lens: 'equidistant', nrings: 7, nseg: 8, clump: 0 };
const SCENES = [
  { seed: 101, lai: 0.8 },
  { seed: 102, lai: 1.5 },
  { seed: 103, lai: 2.5 },
  { seed: 104, lai: 3.5 },
  { seed: 105, lai: 5.0 },
  { seed: 106, lai: 2.0, clump: 0.5 },
  { seed: 107, lai: 3.0, clump: 0.9 },
  { seed: 108, lai: 4.0, clump: 0.9, zonal: false },
  { seed: 109, lai: 2.5, zonal: false },
  { seed: 110, lai: 3.0, lens: 'FC-E8' },
  { seed: 111, lai: 1.2, clump: 0.3, channel: 'Luma' },
  { seed: 112, lai: 3.0, nrings: 6, nseg: 12, channel: 2 },
].map((s) => ({ ...base, ...s }));

const dir = mkdtempSync(join(tmpdir(), 'ff-ref-'));
try {
  SCENES.forEach((s, i) => {
    const scene = Canopy.makeScene({ seed: s.seed, maxLai: s.lai, clump: s.clump });
    const img = Canopy.render(scene, s.lai, s.size);
    writeFileSync(join(dir, `scene_${String(i).padStart(2, '0')}.png`), encodePNG(img.rgba, img.width, img.height));
  });
  writeFileSync(join(dir, 'scenes.json'), JSON.stringify(SCENES));

  const py = spawnSync(process.env.PYTHON || 'python', [join(here, 'gen_golden.py'), corePath, dir],
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  if (py.status !== 0) {
    console.error(py.stderr || py.error);
    process.exit(1);
  }
  const result = JSON.parse(py.stdout);

  const git = spawnSync('git', ['-C', dirname(corePath), 'rev-parse', 'HEAD'], { encoding: 'utf8' });
  const sha = git.status === 0 ? git.stdout.trim() : 'unknown';
  const meta = {
    source: 'realgauravvyas/hemispheR-py',
    commit: sha,
    file: 'core/hemispherR-py.py',
    python: result.python, numpy: result.numpy, pandas: result.pandas, pillow: result.pillow,
    generated: new Date().toISOString().slice(0, 10),
    size: SIZE,
    scenes: result.scenes,
  };
  const js =
    '/* Generated by tools/make_reference.mjs — do not edit by hand.\n' +
    '   What the real hemispheR-py computes on synthetic canopies rendered by canopy.js.\n' +
    '   The page (and CI) re-run the JavaScript port on the same scenes and compare. */\n' +
    '(function (root) {\n' +
    '  var ref = ' + JSON.stringify(meta, null, 1) + ';\n' +
    "  if (typeof module !== 'undefined' && module.exports) module.exports = ref;\n" +
    '  else root.CANOPY_REFERENCE = ref;\n' +
    "})(typeof window !== 'undefined' ? window : globalThis);\n";
  writeFileSync(join(here, '..', 'assets', 'js', 'reference.js'), js);
  console.log(`wrote assets/js/reference.js — ${result.scenes.length} scenes, hemispheR-py @ ${sha.slice(0, 7)}, ` +
    `numpy ${result.numpy}, pandas ${result.pandas}, Pillow ${result.pillow}`);
} finally {
  rmSync(dir, { recursive: true, force: true });
}
